const readlineSync = require("readline-sync");
const chalk = require("chalk");

//ex13, 14, 15:
console.log(
  chalk.greenBright.bgMagenta("  Let's find out How well do you know about Country INDIA!!!  \n")
);

const userName = readlineSync.question(
  chalk.cyanBright("❤️ Please enter your name ❤️\n")
);

console.log(
  chalk.hex("#DEADED")(
    "\nHi " +
    userName +
    ". Get ready for Level 1. \nEnter a/ b/ c for each question to answer. For each correct answer you will get 2 points."
  )
);

//variable declaration for score and question-answers
let score = 0;

const question1 = {
  que: "Which is the Longest river in India? \na.Godavari\nb.Ganga\nc.Brahmaputra",
  ans: "b",
  description: "The Longest river in india is Ganga.",
};

const question2 = {
  que: "What is the Capital of India? \na.Delhi \nb.Mumbai \nc.Bangalore ",
  ans: "a",
  description: "The Capital is Delhi.",
};

const question3 = {
  que: "Which state has the largest population? \na.Uttar Pradesh \nb.Maharashtra\nc.Bihar",
  ans: "a",
  description: "Uttar Pradesh state has the largest population of more than 166 million. It is followed by Maharashtra and Bihar.",
};

const question4 = {
  que: "Which is the National Sports of India? \na.Football \nb.Cricket \nc.Hockey ",
  ans: "c",
  description: "Hockey is considered as India's National sport.",
};

const question5 = {
  que: "India is a federal union comprising twenty-eight states and how many union territories?? \na.6 \nb.7 \nc.8",
  ans: "c",
  description:
    "Presently, India comprises 28 States and 8 Union Territories. India is a democratic country and came into being on 15 August 1947, upon gaining independence.",
};

const question6 = {
  que: "Which is the largest coffee-producing state of India? \na.Kerala \nb.Tamil Nadu \nc.Karnataka",
  ans: "c",
  description: "Karnataka is the largest Coffee-producing state of India with 70.5% and is followed by Kerala, and Tamil Nadu.",
};

const question7 = {
  que: "Which state has the largest area?\na.Madhya Pradesh \nb.Rajasthan \nc.Maharashtra",
  ans: "b",
  description: "In terms of area, Rajasthan is the largest state in India which covers 342,239 sq km and as per Census 2011, the total population of the state is about 68548437.",
};

const question8 = {
  que: "In what state is Elephant Falls located?\na.Mizoram \nb.Meghalaya \nc.Orissa",
  ans: "b",
  description: "It is amongst the most popular falls in the North-East and is located in the outskirts of the capital city of Meghalaya.",
};

const question9 = {
  que: "Which of the following pass has been created by the Indus River?\na.Rohtas Pass \nb.Nathula Pass \nc.Banihal Pass",
  ans: "c",
  description: "Banihal Pass has been created by the Indus River. It is a narrow pass between two mountains generated by a water body. It is located in the Pirpanjal ranges of Jammu and Kashmir.",
};

const question10 = {
  que: " What is the state flower of Haryana?\na.Lotus \nb.Rhododendron \nc.Golden Showere",
  ans: "a",
  description: "Lotus or Water Lily is the state flower of Haryana. It is an aquatic plant with broad floating green leaves and bright fragrant flowers that grow only in shallow waters.",
};
//saving all questions in array
const questionSet1 = [
  question1,
  question2,
  question3,
  question4,
  question5,
  question6,
  question7,
  question8,
  question9,
  question10,
];
//defining Leaderboard
const highScore = [
  { nameH: "Sonu", scoreH: "20" },
  { nameH: "Vaiju", scoreH: "18" },
  { nameH: "Anku", scoreH: "16" },
  { nameH: "Pinki", scoreH: "14" },
];

//posting quiz and validating answers
for (let i = 0; i < questionSet1.length; i++) {
  if (i === 3) {
    if (score >= 4) {
      console.log("Congratulations! You have entered Level 2 🤩");
    } else {
      console.log("Aww! you failed level 1");
      break;
    }
  }
  if (i === 6) {
    if (score >= 8) {
      console.log(
        "Congratulations! You have entered Final Level 🤩. Get ready for the toughest questions."
      );
    } else {
      console.log("Hurry! you failed level 2");
      break;
    }
  }
  checkScore(
    i + 1,
    questionSet1[i].que,
    questionSet1[i].ans,
    questionSet1[i].description
  );
}

//posting leaderboard
console.log(chalk.keyword("orange").bold("\n*****Check out Leaderboard*****"));


//compare score with high scores
let scoreBeaten = false;
let index = highScore.findIndex((obj) => score >= obj.scoreH)
console.log(index)
if (index === -1) {
  highScore.push({
    nameH: `${userName}`,
    scoreH: `${score}`,
  })
} else {
  scoreBeaten = true;
  highScore.splice(index, 0, {
    nameH: `${userName}`,
    scoreH: `${score}`,
  });
}
printScoreBoard(highScore);
console.log("---------------------------------");

//Printing final score
console.log(chalk.hex("#DEADED").bold("Yay! Your Final Score is " + score));
//if score is beaten, print leaderboard with username and score

if (scoreBeaten) {
  console.log(
    chalk.bold.keyword("pink")(
      "Congratulations " + userName + " 🥳 , you are very good at GK 😍"
    )
  );

  console.log(chalk.keyword("orange").bold("\n*****Leaderboard*****"));
  printScoreBoard(highScore);
} else {
  console.log(
    chalk.bold.hex("#DEADED")(
      "Sorry " + userName + ", you were so close to know some basic GK of India"
    )
  );
}

//function to validate answers and update score
function checkScore(queNo, checkQue, checkAns, description) {
  const userAns = readlineSync.keyIn(
    chalk.cyanBright("\n" + queNo + ") " + checkQue + "\n"),
    { limit: "$<a-c>" }
  );
  if (userAns === checkAns) {
    console.log(chalk.green("You are absolutely right. You get 2 points 🎉"));
    score += 2;
  } else {
    console.log(chalk.redBright(`You are wrong.\n${description}`));
  }
  console.log(chalk.yellowBright("Your current score is " + score));
  console.log("---------------------\n");
}

//function to print leaderBoard
function printScoreBoard(highScore) {
  highScore.forEach((obj) => {
    console.log(
      chalk
        .keyword("orange")
        .bold(obj.nameH + " : " + obj.scoreH)
    );
  })
}
